name: grocery_store
description: A new Flutter project.
version: 1.0.2+3

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  awesome_card: ^1.1.0
  carousel_pro: ^1.0.0
  carousel_slider: ^3.0.0
  cloud_firestore: ^1.0.1
  cupertino_icons: ^1.0.2
  extended_image: ^3.0.0
  firebase_analytics: ^7.1.1
  firebase_auth: ^1.0.1
  firebase_core: ^1.0.1
  firebase_dynamic_links: ^0.8.0
  firebase_messaging: ^9.0.0
  firebase_storage: ^8.0.0
  flushbar: ^1.10.4
  flutter_bloc: ^6.1.3
  flutter_credit_card: ^0.1.4
  flutter_email_sender: ^5.0.0
  flutter_local_notifications: ^5.0.0-nullsafety.1
  flutter_share: ^1.0.5
  flutter_svg: ^0.19.3
  font_awesome_flutter: ^8.12.0
  full_screen_image: ^1.0.2
  google_fonts: ^2.0.0
  google_sign_in: ^5.0.0
  http: ^0.13.0
  image_cropper: ^1.4.0
  image_picker: ^0.7.3
  intl: ^0.17.0
  introduction_screen: ^2.0.0
  path_provider: ^2.0.1
  shared_preferences: ^2.0.5
  shimmer: ^1.1.2
  smooth_star_rating: ^1.1.1
  stripe_payment: ^1.0.10
  transparent_image: ^1.0.0
  uuid: ^3.0.1
  razorpay_flutter: ^1.2.5
  apple_sign_in: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/banners/
    - assets/banners/easy_returns.svg
